// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.geekerstar.netty.manual.$34.proto;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    String getName();

    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
