// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.geekerstar.netty.manual.$34.proto;

public final class Hello {
    private Hello() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HelloRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HelloRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HelloResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HelloResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Player_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Player_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013Hello.proto\"\034\n\014HelloRequest\022\014\n\004name\030\001 " +
                        "\001(\t\"I\n\rHelloResponse\022\016\n\006result\030\001 \001(\010\022\017\n\007" +
                        "message\030\002 \001(\t\022\027\n\006player\030\003 \001(\0132\007.Player\"\026" +
                        "\n\006Player\022\014\n\004name\030\001 \001(\tB\"\n\036com.imooc.nett" +
                        "y.core.$34.protoP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_HelloRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_HelloRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloRequest_descriptor,
                new String[]{"Name",});
        internal_static_HelloResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_HelloResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloResponse_descriptor,
                new String[]{"Result", "Message", "Player",});
        internal_static_Player_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Player_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Player_descriptor,
                new String[]{"Name",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
