// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.geekerstar.netty.manual.$34.proto;

/**
 * <pre>
 * HelloResponse
 * </pre>
 * <p>
 * Protobuf type {@code HelloResponse}
 */
public final class HelloResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:HelloResponse)
        HelloResponseOrBuilder {
    // Use HelloResponse.newBuilder() to construct.
    private HelloResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private HelloResponse() {
        result_ = false;
        message_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private HelloResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        result_ = input.readBool();
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        message_ = s;
                        break;
                    }
                    case 26: {
                        Player.Builder subBuilder = null;
                        if (player_ != null) {
                            subBuilder = player_.toBuilder();
                        }
                        player_ = input.readMessage(Player.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(player_);
                            player_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Hello.internal_static_HelloResponse_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Hello.internal_static_HelloResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        HelloResponse.class, Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;

    /**
     * <code>optional bool result = 1;</code>
     */
    public boolean getResult() {
        return result_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;

    /**
     * <code>optional string message = 2;</code>
     */
    public String getMessage() {
        Object ref = message_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            message_ = s;
            return s;
        }
    }

    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
    getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            message_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PLAYER_FIELD_NUMBER = 3;
    private Player player_;

    /**
     * <code>optional .Player player = 3;</code>
     */
    public boolean hasPlayer() {
        return player_ != null;
    }

    /**
     * <code>optional .Player player = 3;</code>
     */
    public Player getPlayer() {
        return player_ == null ? Player.getDefaultInstance() : player_;
    }

    /**
     * <code>optional .Player player = 3;</code>
     */
    public PlayerOrBuilder getPlayerOrBuilder() {
        return getPlayer();
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (result_ != false) {
            output.writeBool(1, result_);
        }
        if (!getMessageBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
        }
        if (player_ != null) {
            output.writeMessage(3, getPlayer());
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (result_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(1, result_);
        }
        if (!getMessageBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
        }
        if (player_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getPlayer());
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof HelloResponse)) {
            return super.equals(obj);
        }
        HelloResponse other = (HelloResponse) obj;

        boolean result = true;
        result = result && (getResult()
                == other.getResult());
        result = result && getMessage()
                .equals(other.getMessage());
        result = result && (hasPlayer() == other.hasPlayer());
        if (hasPlayer()) {
            result = result && getPlayer()
                    .equals(other.getPlayer());
        }
        return result;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getResult());
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        if (hasPlayer()) {
            hash = (37 * hash) + PLAYER_FIELD_NUMBER;
            hash = (53 * hash) + getPlayer().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static HelloResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static HelloResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static HelloResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static HelloResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static HelloResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static HelloResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static HelloResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static HelloResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static HelloResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static HelloResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(HelloResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * HelloResponse
     * </pre>
     * <p>
     * Protobuf type {@code HelloResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:HelloResponse)
            HelloResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Hello.internal_static_HelloResponse_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Hello.internal_static_HelloResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            HelloResponse.class, Builder.class);
        }

        // Construct using com.geekerstar.netty.mooc.core.$34.proto.HelloResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            result_ = false;

            message_ = "";

            if (playerBuilder_ == null) {
                player_ = null;
            } else {
                player_ = null;
                playerBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Hello.internal_static_HelloResponse_descriptor;
        }

        public HelloResponse getDefaultInstanceForType() {
            return HelloResponse.getDefaultInstance();
        }

        public HelloResponse build() {
            HelloResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public HelloResponse buildPartial() {
            HelloResponse result = new HelloResponse(this);
            result.result_ = result_;
            result.message_ = message_;
            if (playerBuilder_ == null) {
                result.player_ = player_;
            } else {
                result.player_ = playerBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof HelloResponse) {
                return mergeFrom((HelloResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(HelloResponse other) {
            if (other == HelloResponse.getDefaultInstance()) return this;
            if (other.getResult() != false) {
                setResult(other.getResult());
            }
            if (!other.getMessage().isEmpty()) {
                message_ = other.message_;
                onChanged();
            }
            if (other.hasPlayer()) {
                mergePlayer(other.getPlayer());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            HelloResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (HelloResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private boolean result_;

        /**
         * <code>optional bool result = 1;</code>
         */
        public boolean getResult() {
            return result_;
        }

        /**
         * <code>optional bool result = 1;</code>
         */
        public Builder setResult(boolean value) {

            result_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional bool result = 1;</code>
         */
        public Builder clearResult() {

            result_ = false;
            onChanged();
            return this;
        }

        private Object message_ = "";

        /**
         * <code>optional string message = 2;</code>
         */
        public String getMessage() {
            Object ref = message_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            message_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {

            message_ = getDefaultInstance().getMessage();
            onChanged();
            return this;
        }

        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            message_ = value;
            onChanged();
            return this;
        }

        private Player player_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                Player, Player.Builder, PlayerOrBuilder> playerBuilder_;

        /**
         * <code>optional .Player player = 3;</code>
         */
        public boolean hasPlayer() {
            return playerBuilder_ != null || player_ != null;
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Player getPlayer() {
            if (playerBuilder_ == null) {
                return player_ == null ? Player.getDefaultInstance() : player_;
            } else {
                return playerBuilder_.getMessage();
            }
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Builder setPlayer(Player value) {
            if (playerBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                player_ = value;
                onChanged();
            } else {
                playerBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Builder setPlayer(
                Player.Builder builderForValue) {
            if (playerBuilder_ == null) {
                player_ = builderForValue.build();
                onChanged();
            } else {
                playerBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Builder mergePlayer(Player value) {
            if (playerBuilder_ == null) {
                if (player_ != null) {
                    player_ =
                            Player.newBuilder(player_).mergeFrom(value).buildPartial();
                } else {
                    player_ = value;
                }
                onChanged();
            } else {
                playerBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Builder clearPlayer() {
            if (playerBuilder_ == null) {
                player_ = null;
                onChanged();
            } else {
                player_ = null;
                playerBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public Player.Builder getPlayerBuilder() {

            onChanged();
            return getPlayerFieldBuilder().getBuilder();
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        public PlayerOrBuilder getPlayerOrBuilder() {
            if (playerBuilder_ != null) {
                return playerBuilder_.getMessageOrBuilder();
            } else {
                return player_ == null ?
                        Player.getDefaultInstance() : player_;
            }
        }

        /**
         * <code>optional .Player player = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Player, Player.Builder, PlayerOrBuilder>
        getPlayerFieldBuilder() {
            if (playerBuilder_ == null) {
                playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Player, Player.Builder, PlayerOrBuilder>(
                        getPlayer(),
                        getParentForChildren(),
                        isClean());
                player_ = null;
            }
            return playerBuilder_;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:HelloResponse)
    }

    // @@protoc_insertion_point(class_scope:HelloResponse)
    private static final HelloResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new HelloResponse();
    }

    public static HelloResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloResponse>
            PARSER = new com.google.protobuf.AbstractParser<HelloResponse>() {
        public HelloResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new HelloResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<HelloResponse> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HelloResponse> getParserForType() {
        return PARSER;
    }

    public HelloResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

