// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.geekerstar.netty.manual.$34.proto;

public interface HelloResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:HelloResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>optional string message = 2;</code>
     */
    String getMessage();

    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
    getMessageBytes();

    /**
     * <code>optional .Player player = 3;</code>
     */
    boolean hasPlayer();

    /**
     * <code>optional .Player player = 3;</code>
     */
    Player getPlayer();

    /**
     * <code>optional .Player player = 3;</code>
     */
    PlayerOrBuilder getPlayerOrBuilder();
}
