// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.geekerstar.netty.manual.$997.proto;

public interface LoginResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LoginResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     */
    boolean getResult();

    /**
     * <code>optional string message = 2;</code>
     */
    String getMessage();

    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
