// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.geekerstar.netty.manual.$997.proto;

public interface LoginRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LoginRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     */
    String getUsername();

    /**
     * <code>optional string username = 1;</code>
     */
    com.google.protobuf.ByteString
    getUsernameBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    String getPassword();

    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
    getPasswordBytes();
}
