// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.geekerstar.netty.manual.$997.proto;

public final class Mahjong {
    private Mahjong() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rMahjong.proto\"2\n\014LoginRequest\022\020\n\010usern" +
                        "ame\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"0\n\rLoginResp" +
                        "onse\022\016\n\006result\030\001 \001(\010\022\017\n\007message\030\002 \001(\tB#\n" +
                        "\037com.geekerstar.netty.mooc.core.$997.protoP\001b\006prot" +
                        "o3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_LoginRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_LoginRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginRequest_descriptor,
                new String[]{"Username", "Password",});
        internal_static_LoginResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_LoginResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginResponse_descriptor,
                new String[]{"Result", "Message",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
